# This is a basic workflow to help you get started with Actions

name: Github Action CI/CD Test
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login docker registry(Github Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          psuh: true
          tag: ghcr.io/${{ secrets.GHCR_USER }}/ubuntu-22.04--systemd:latest
