# This is a basic workflow to help you get started with Actions

name: Github Action CI/CD Test
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: [self-hosted, kube-master]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login docker registry(Github Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 192.168.0.170:5000/${{ secrets.GHCR_USER }}/ubuntu-22.04--systemd:latest
      
