# This is a basic workflow to help you get started with Actions

name: Github Action CI/CD Test
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: [self-hosted, kube-master]
    steps:
      - name: command test
        run: |
          touch test.txt
          echo "!! TEST !!" > test.txt
